# Generated by Django 5.2.5 on 2025-08-15 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Security",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=16, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("sector", models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Default", max_length=64)),
                ("currency", models.CharField(default="MWK", max_length=8)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="core.account",
                    ),
                ),
                (
                    "security",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.security"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CorporateAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ctype", models.CharField(max_length=16)),
                ("ex_date", models.DateField(blank=True, null=True)),
                ("pay_date", models.DateField(blank=True, null=True)),
                (
                    "ratio",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=16, null=True
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=16, null=True
                    ),
                ),
                (
                    "security",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.security"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ttype",
                    models.CharField(
                        choices=[
                            ("BUY", "BUY"),
                            ("SELL", "SELL"),
                            ("DIV", "DIVIDEND"),
                            ("FEE", "FEE"),
                            ("SPLIT", "SPLIT"),
                        ],
                        default="BUY",
                        max_length=8,
                    ),
                ),
                (
                    "qty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=16),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=4, default=0, max_digits=16),
                ),
                (
                    "fees",
                    models.DecimalField(decimal_places=4, default=0, max_digits=16),
                ),
                ("date", models.DateField()),
                ("note", models.TextField(blank=True)),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="core.position",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("close", models.DecimalField(decimal_places=4, max_digits=16)),
                ("volume", models.BigIntegerField(default=0)),
                (
                    "security",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="core.security",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("security", "date")},
            },
        ),
    ]
